title = "DPCN"
baseURL = "https://www.dpcn.us"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-156007492-2"
enableRobotsTXT = true

[permalinks]
  post = "/:year/:month/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/radio-48.ico"
  description = "Digital Private Calling Network"
  facebook = "https://www.facebook.com/DPCN-110692447127815"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  featured_image = "/images/sound-speaker-radio-microphone-484.jpg"
  recent_posts_number = 5
  custom_css = ["css/custom.css"]
  mainSections = ["post"]

[frontmatter]
  date = ["date", "publishDate", "lastmod", ":fileModTime"]
